---
title: "assignment-1"
author: "Helle"
date: "2023-02-16"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```





Random bot - capitalist (coin holder)

```{r}

random_agent <- function(bias) {
  choice <- rbinom(1,1, bias)
  return(choice)
}

bias <- 0.5

random_choice <- random_agent(bias)
random_choice

```
Running random agent 120 trials 

```{r}
trials <- 120

random_choice <- rep(NA, trials)

for(trial in seq(trials)) {
  random_choice[trial] <- random_agent(bias)
}

df1 <- tibble(trial = seq(trials), choice = random_choice)



```

Our first strategy: win-shift-lose-stay 


```{r}
#Agent with a strong reaction to loosing, meaning it sticks more to the strategy of staying when losing. 
wsls_agent_strong <- function(prev_choice, feedback, bias_lose, bias_win) {
  if (feedback == 0) { #lose stay
    if(prev_choice == 0) { 
      choice = rbinom(1, 1, (1-bias_lose))}
    if(prev_choice == 1) { 
      choice = rbinom(1, 1, bias_lose)}
      }
  else if (feedback == 1) { #win shift
    if(prev_choice == 0) { 
      choice = rbinom(1, 1, bias_win)}
    if(prev_choice == 1) { 
      choice = rbinom(1, 1, (1-bias_win))}
  }
  return(choice)  }

```

playing wsls_strong against our random agent 

```{r}
#random agent bias
bot_bias <- 0.7
bias_lose <- 0.9
bias_win <- 0.7



self <- rep(NA, trials)
bot <- rep(NA, trials)

self[1] <- random_agent(0.5)

for(trial in seq(trials)) {
  bot[trial] <- random_agent(bot_bias)
}

for (trial in 2:trials){
  if(self[trial-1] == bot[trial-1]) {
    feedback = 1
  } else {feedback = 0}
  self[trial] <- wsls_agent_strong(prev_choice = self[trial-1], feedback, bias_lose, bias_win)
}


print(self)

```
```{r}
#Sanity check plot
performance_df <- tibble(self, bot, trial = seq(trials), feedback = as.numeric(self==bot))

performance_df %>% ggplot() +
  geom_line(color = "red", aes(trial, self)) +
  geom_line(color = "blue", aes(trial, bot))



```




Plot the strong wsls 

```{r}
performance_df <- tibble(self, bot, trial = seq(trials), feedback = as.numeric(self==bot))

performance_df <- performance_df %>% 
  mutate(cumulative_self = cumsum(feedback)/seq_along(feedback))



```




