---
title: "Stan model implementation"
author: "Astrid Nørgaard Fonager"
date: "2023-03-01"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(pacman)

pacman::p_load(tidyverse,
        here,
        posterior,
        cmdstanr,
        brms, tidybayes, future, purrr, furrr, prettydoc)
```

# FUNCTIONS

```{r agent functions}

# Random bot
random_agent <- function(bias = 0.7) {
  choice <- rbinom(1,1, bias)
  return(choice)
}

# Win-shift-lose-stay agent
win_shift_agent <- function(prev_choice, feedback, bias_lose, bias_win) {
  if (feedback == 0) { #lose stay
    if(prev_choice == 0) { 
      choice = rbinom(1, 1, (1-bias_lose))}
    if(prev_choice == 1) { 
      choice = rbinom(1, 1, bias_lose)}
      }
  else if (feedback == 1) { #win shift
    if(prev_choice == 0) { 
      choice = rbinom(1, 1, bias_win)}
    if(prev_choice == 1) { 
      choice = rbinom(1, 1, (1-bias_win))}
  }
  return(choice)  
}
```


```{r simulation function RA}

sim_vs_random <- function(agents, trials, bias_lose, bias_win){
  
  feedback <- array(NA, c(agents, trials))
  performance_df <- data_frame()
  
  for (agent in 1:agents){
    self <- rep(NA, trials)
    bot <- rep(NA, trials)
  
    self[1] <- random_agent(0.5)
    
    for(trial in seq(trials)) {
      bot[trial] <- random_agent()
    }
    
    for (trial in 2:trials){
      if(self[trial-1] == bot[trial-1]) {
        feedback[agent, trial] = 1
      } 
      else {
        feedback[agent, trial] = 0
      }
      self[trial] <- win_shift_agent(prev_choice = self[trial-1], 
                                      feedback = feedback[agent, trial], 
                                      bias_lose = bias_lose, 
                                      bias_win = bias_win)
    }
    
    df_temp <- tibble(agent = agent, self, bot, trial = seq(trials), 
                      feedback = as.numeric(self==bot)) %>% 
      mutate(cumulative_self = cumsum(feedback)/seq_along(feedback),
             cumulative_bot = cumsum(1-feedback)/seq_along(feedback)) 
    
    performance_df <- rbind(performance_df, df_temp)
    
  }
  
  return(performance_df)
}
```


```{r simulation and fitting function}

sim_d_and_fit <- function(seed, trials, bias_win, bias_lose, clean = TRUE) {
  for (t in seq(trials)) {
    temp <-  sim_vs_random(agents = 1,
                           trials = trials, 
                           bias_lose = bias_lose,
                           bias_win = bias_win)
  }
  
  data <-  list(
    t = trials,
    choice = lead(temp$self, 1),
    self = temp$self,
    other = temp$bot
  )
  
  data$choice[t] <- 0

  samples <- model$sample(
    data = data,
    seed = seed,
    chains = 1,
    parallel_chains = 1,
    threads_per_chain = 1,
    iter_warmup = 1000,
    iter_sampling = 2000,
    refresh = 0,
    max_treedepth = 20,
    adapt_delta = 0.99,
  )
  
  
  if(clean == TRUE) {
    draws_df <- as_draws_df(samples$draws())
    df <- tibble(bias_winEst = draws_df$bias_win_posterior, 
                 bias_loseEst = draws_df$bias_lose_posterior, 
                 bias_winTrue = bias_win, 
                 bias_loseTrue = bias_lose,
                 prior_preds_LR = draws_df$prior_preds_LR,
                 prior_preds_LL = draws_df$prior_preds_LL,
                 prior_preds_WR = draws_df$prior_preds_WR,
                 prior_preds_WL = draws_df$prior_preds_WL,
                 post_preds_LR = draws_df$post_preds_LR,
                 post_preds_LL = draws_df$post_preds_LL,
                 post_preds_WR = draws_df$post_preds_WR,
                 post_preds_WL = draws_df$post_preds_WL)
  
    return(df)
  }
  
  else if(clean == FALSE){
    return(samples)
  }

}

```

# FITTING THE MODEL

```{r import model}
setwd("/Users/astridnorgaardfonager/Documents/CogSci/8th semester/ACM/Assignments/A2/")

## Specify where the model is
file <- file.path("stan/model1.stan")
model <- cmdstan_model(file, 
                     cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1")) 


```


```{r test fitting}
test <- sim_d_and_fit(seed = 1000, trials = 100, bias_win = 0.7, bias_lose = 0.9)
```

# MODEL QUALITY

## Sampling issues

```{r check for sampling issues}

#Fit 
samples <- sim_d_and_fit(seed = 1000, trials = 100, bias_win = 0.7, bias_lose = 0.9, clean = FALSE)

# Diagnose
samples$cmdstan_diagnose()

# Plot hairy caterpillars
draws_df <- as_draws_df(samples$draws())

ggplot(draws_df, aes(.iteration, bias_win, group = .chain, color=.chain)) + 
  geom_line() +
  labs(title = "Bias_win") +
  theme_classic()

ggplot(draws_df, aes(.iteration, bias_lose, group = .chain, color=.chain)) + 
  geom_line() +
  labs(title = "Bias_lose") +
  theme_classic()

# not correlated
ggplot(draws_df, aes(bias_lose, bias_win, group = .chain, color=.chain)) + 
  geom_point(alpha= 0.3) +
  labs(title = "Bias_win") +
  theme_classic()

```
